### ISSUE TITLE
[Bug] Subscription showing as Active when it is actually Canceled 

### ISSUE THREAD

**Issue by brian-equilife** [fivetran/dbt_recharge#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I've fount multiple occurrences where subscriptions in the `recharge__subscription_overview` table where subscriptions shows as 'ACTIVE' when it should show as 'CANCELED'.

Example:
Here is the record for a subscription in `recharge__subscription_overview`
`[{
  "subscription_id": "222460739",
  "customer_id": "82331755",
  "address_id": "89136022",
  "subscription_created_at": "2022-02-27 20:55:52.000000 UTC",
  "external_product_id_ecommerce": null,
  "external_variant_id_ecommerce": null,
  "product_title": "Fatlossity",
  "variant_title": "",
  "sku": null,
  "price": "84.15",
  "quantity": "1",
  "subscription_status": "ACTIVE",
  "charge_interval_frequency": "12",
  "order_interval_unit": "week",
  "order_interval_frequency": "12",
  "order_day_of_month": null,
  "order_day_of_week": null,
  "expire_after_specific_number_of_charges": null,
  "subscription_updated_at": "2022-02-27 20:55:52.000000 UTC",
  "subscription_next_charge_scheduled_at": "2022-05-22 04:00:00.000000 UTC",
  "subscription_cancelled_at": null,
  "cancellation_reason": null,
  "cancellation_reason_comments": null,
  "_fivetran_synced": "2022-03-05 23:16:43.646000 UTC",
  "is_most_recent_record": "true",
  "count_successful_charges": null,
  "count_queued_charges": null,
  "charges_until_expiration": null,
  "charge_interval_frequency_days": "84"
}]`

And here is the record for the same subscription in the Recharge Source table `subscription`
`[{
  "id": "222460739",
  "_fivetran_synced": "2022-03-08 07:11:36.280000 UTC",
  "address_id": "89136022",
  "cancellation_reason": null,
  "cancellation_reason_comments": null,
  "cancelled_at": "2022-03-08 06:18:46.000000 UTC",
  "charge_interval_frequency": "12",
  "created_at": "2022-02-27 20:55:52.000000 UTC",
  "customer_id": "82331755",
  "expire_after_specific_number_of_charges": null,
  "is_deleted": null,
  "next_charge_scheduled_at": null,
  "number_charges_until_expiration": null,
  "order_day_of_month": null,
  "order_day_of_week": null,
  "order_interval_frequency": "12",
  "order_interval_unit": "week",
  "price": "84.15",
  "product_title": "Fatlossity",
  "property_charge_interval_frequency": null,
  "property_charge_interval_unit_type": null,
  "property_financing": null,
  "property_item_title": null,
  "property_number_charges_until_expiration": null,
  "property_shipping_interval_frequency": null,
  "property_shipping_interval_unit_type": null,
  "quantity": "1",
  "shopify_product_id": "4440296620117",
  "shopify_variant_id": "31513171525717",
  "sku": null,
  "status": "CANCELLED",
  "updated_at": "2022-03-08 06:18:48.000000 UTC",
  "variant_title": "",
  "_fivetran_deleted": "true",
  "property_is_subscription": "1",
  "property_item_handle": null,
  "property_frequency": null,
  "external_product_id_ecommerce": null,
  "external_variant_id_ecommerce": null,
  "property_subscription_id": null
}]`

### Expected behavior

Based on my understanding of how these rollups work I would have expected the record in table `recharge__subscription_overview` to show as "CANCELED" to match that shown in `subscription`

### dbt Project configurations

No custom configurations related to the recharge package.  Using the default settings.

### Package versions

packages:
  - package: fivetran/shopify
    version: [">=0.8.0", "<0.9.0"] # using ranges to capture non-breaking changes automatically
  - package: fivetran/recharge
    version: [">=0.1.0", "<0.2.0"]

### What database are you using dbt with?

bigquery

### dbt Version

dbt version 1.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
hi there @brian-equilife thanks for taking the time to open this issue! 

so the `recharge__subscription_overview` model actually [selects](https://github.com/fivetran/dbt_recharge/blob/main/models/recharge__subscription_overview.sql#L1-L5) from the `subscription_history` source table and _not_ `subscription`. could you share the most recent record for subscription `222460739` in the `subscription_history` table? i'm curious if the status is reflected inaccurately there ... 

also, how often are you running the model?

**Comment by fivetran-joemarkiewicz** [comment]
Marking this issue as blocked and stale until we are able to gin a better understanding of the issue following the above inquiry.

**Comment by fivetran-catfritz** [comment]
Making a note here. I believe the issue stems from [this source model](https://github.com/fivetran/dbt_recharge_source/blob/main/models/stg_recharge__subscription_history.sql). I need to update the way `is_most_recent_record` is calculated to use `updated_at` instead of `_fivetran_synced`. We should use this instead since`updated_at` is actually part of the primary key for that table. That would explain the discrepancy. I can also see the discrepancy in the `updated_at` field of the two examples provided.

**Comment by fivetran-catfritz** [comment]
Hi @brian-equilife, thanks for flagging this issue. I have created a test branch that should the resolve the discrepancy. The issue was in the source, and this test branch uses this updated source. 

If you are able to test it out and let us know your feedback, it would be much appreciated! You can install the test branch by replacing the normal dbt_recharge section in your `packages.yml` with the following:
```yml
  - git: https://github.com/fivetran/dbt_recharge.git
    revision: feature/update-joins
    warn-unpinned: false
```

**Comment by fivetran-catfritz** [comment]
HI @brian-equilife we have released what I believe is the fix for this, so closing the issue. If you have any additional feedback, feel free to ping us in this issue!

**Comment by brian-equilife** [comment]
@fivetran-catfritz @fivetran-jamie @fivetran-joemarkiewicz I missed all of these notifications - I am so sorry.  

I updated to the most recent release and the issue persists.  I did further digging on my end.  And as a great poet once said "I'm the problem - It's me". When I log in to Recharge and use their web interface I am unable to locate subscription 222460739, the one noted in the original ticket.  And when I look at the replicated tables there are no history records for this subscription though there is a single record in the subscription table (@fivetran-jamie this answers your earlier inquiry).  I manually reviewed the timeline within the Recharge web interface and it shows the subscription being deleted by one of our customer service reps.  It seems like a messy way for Recharge to handle this on the back end since this subscription was indeed part of an order that shipped.
